### ISSUE TITLE
Apio 0.2.3 LOAD_CONFIG_DATA flag

### ISSUE THREAD

**Issue by Jesus89** [set-soft/apio-debian#2]
Hi

From **apio 0.2.3**, a new flag configuration is needed in order to package the application in debian.

This flag is LOAD_CONFIG_DATA. It requires a sed-like operation to change it to True before package: https://github.com/FPGAwars/apio/blob/develop/apio/__init__.py#L21.

The reason is: if you have apt-apio installed, and then a pip-apio (in the console or in Icestudio) the pip-apio package system is not isolated because pip-apio looks in /etc/apio.json PKG_DIRs, and this must be checked only in the apt-apio distribution.

Regards.

**Comment by set-soft** [comment]
Ok, now the package patches apio/__init__.py
